### ISSUE TITLE
settings : 프로젝트를 생성하고 환경을 구성한다

### ISSUE THREAD

**Issue by Joylish** [ToyMakers/todo-schedule-backend#2]
# Todo
- [x]  [피드백 바탕으로 db 스키마 재설계](https://github.com/ToyMakers/todo-schedule-api-docs/issues/7) 
- [x]  [피드백 바탕으로 api 문서(gitbook) 수정](https://github.com/ToyMakers/todo-schedule-api-docs/tree/3758430f1dae0b3342e5bdb816ba2e790e7892f4) 
- [x]  프로젝트 생성 4fb45f1b38e5aec23a966cd3f226e6a49de4852f
- [x]  mysql 설정 be5fe2a6df3168948428edd42e043a637a2000ec

# 공부
- [ ] ear, jar, war
- [x] gradle compile -> implementation
   -  [log.bluayer의 [Gradle] implementation vs compile](https://hack-jam.tistory.com/13)
   -  내가 생성한 spring boot 프로젝트에서 build.gradle에 compile을 쓰면 build error가 났다. 그 이유는 `compile`이 deprecated되었기 때문이었다. gradle 7이상부터는 `compile`은 `implementataion`로 써야했다. 찾아보니 `testCompile` 도 deprecated되어 `testImplementation`로 작성해야 했다.
   -  [stackoverflow의 What's the difference between implementation, api and compile in Gradle?](https://stackoverflow.com/questions/44493378/whats-the-difference-between-implementation-api-and-compile-in-gradle/48388463#48388463)
   - [gradle 공식문서](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation)
- [ ] MyBatis vs Spring JDBC
   - [benelog의 mybatis 대비 spring jdbc](https://github.com/benelog/spring-jdbc-tips/blob/master/framework-compare.md)
- [ ] Hibernate의 ddl-auto
   - [twer의 ddl-auto](https://twer.tistory.com/entry/JPA-Hibernate%EC%9D%98-ddl-auto)
